# Generated by Django 3.0.8 on 2020-07-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAreaORI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('activo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('contacto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MtipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.CharField(max_length=60)),
                ('nombre_corto', models.CharField(max_length=40)),
                ('activo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MUbigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('distrito', models.CharField(max_length=40)),
                ('estado', models.IntegerField()),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegDocumentosORI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_pnp', models.CharField(max_length=60)),
                ('codigo_arequipa', models.IntegerField()),
                ('codigo_lima', models.IntegerField()),
                ('unidad', models.IntegerField()),
                ('descripcion_larga', models.TextField()),
                ('descripcion', models.TextField()),
                ('nombre_corto', models.CharField(max_length=50)),
                ('gran_unidad', models.CharField(max_length=50)),
                ('divisiones', models.CharField(max_length=50)),
                ('tipo_unidad', models.IntegerField()),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('correoInstitucional', models.EmailField(max_length=254)),
                ('correoAlterno', models.EmailField(max_length=254)),
                ('redSocial', models.CharField(max_length=80)),
                ('contacto', models.CharField(max_length=80)),
                ('n_orden', models.IntegerField()),
                ('codigo_historico', models.IntegerField()),
                ('activo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('observacion', models.TextField()),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tramite.MUbigeo')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('tipoDocumento', models.IntegerField()),
                ('n_documento', models.IntegerField()),
                ('fecha_documento', models.DateField()),
                ('unidadEntrega', models.CharField(max_length=80)),
                ('quien_entrega', models.CharField(max_length=80)),
                ('area_destino', models.CharField(max_length=50)),
                ('encargado', models.CharField(max_length=60)),
                ('contenido', models.TextField()),
                ('unidad_Destino', models.CharField(max_length=60)),
                ('documento_tramitado', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('archivo', models.CharField(max_length=100)),
                ('ruta', models.FileField(upload_to='Documentos/')),
                ('numero_Hoja', models.IntegerField()),
                ('activo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('observacion', models.TextField()),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tramite.MAreaORI')),
                ('id_tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tramite.MtipoDocumento')),
                ('id_unidadEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tramite.RegDocumentosORI')),
            ],
        ),
    ]
