# Generated by Django 3.0.8 on 2020-08-01 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tramite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MUserGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codGrado', models.IntegerField()),
                ('Grado', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Clase', models.CharField(max_length=50)),
                ('OrdClase', models.IntegerField()),
                ('Categoria', models.CharField(max_length=50)),
                ('OrdCategoria', models.IntegerField()),
                ('Jerarquia', models.CharField(max_length=50)),
                ('OrdJerarquia', models.IntegerField()),
                ('Estado', models.IntegerField()),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MUserRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Estado', models.IntegerField()),
                ('obs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cip', models.IntegerField()),
                ('idGrado', models.IntegerField()),
                ('Grado', models.CharField(max_length=50)),
                ('ApePaterno', models.CharField(max_length=50)),
                ('ApeMaterno', models.CharField(max_length=50)),
                ('Nombres', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(upload_to='img/')),
                ('Administrador', models.BooleanField()),
                ('idRol', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('estado', models.IntegerField()),
                ('MotivoBaja', models.TextField()),
                ('obs', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
