# Generated by Django 3.0.8 on 2020-08-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tramite', '0002_muser_musergrado_muserrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='mareaori',
            options={'verbose_name_plural': 'Área'},
        ),
        migrations.AlterModelOptions(
            name='mtipodocumento',
            options={'verbose_name_plural': 'TipoDocumentos'},
        ),
        migrations.AlterModelOptions(
            name='muser',
            options={'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='musergrado',
            options={'verbose_name_plural': 'Grado'},
        ),
        migrations.AlterModelOptions(
            name='muserrol',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='muser',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tramite.MUserRol'),
        ),
    ]
