# Generated by Django 3.0.8 on 2020-08-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramite', '0003_auto_20200805_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='archivo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='ruta',
            field=models.FileField(null=True, upload_to='Documentos/'),
        ),
    ]
