# Generated by Django 3.0.8 on 2020-08-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramite', '0004_auto_20200806_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='id_unidadEntrega',
        ),
        migrations.AlterField(
            model_name='documentos',
            name='documento_tramitado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
